//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Scripts/Input/InputActions/QuestSceneInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @QuestSceneInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @QuestSceneInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""QuestSceneInputActions"",
    ""maps"": [
        {
            ""name"": ""QuestScene"",
            ""id"": ""32b71022-ccfe-437a-96c2-5458b717aad6"",
            ""actions"": [
                {
                    ""name"": ""OpenMenu"",
                    ""type"": ""Button"",
                    ""id"": ""2d20a2c5-1649-4889-8fb6-e9bfdcf954cc"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Return"",
                    ""type"": ""Button"",
                    ""id"": ""fc16678f-b565-4f55-99db-8956e16e08d5"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""930224cc-94b1-404c-a2a7-def48cb0fe3e"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";New Control Scheme"",
                    ""action"": ""OpenMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f50c8e9d-b56e-445a-95d0-9ef215d6a94a"",
                    ""path"": ""<Joystick>/{Menu}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""66065d1f-a6a1-4e91-b18c-7c3efbf4bdac"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Return"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3853d67b-56b7-4113-9dc5-a5c3a3787b39"",
                    ""path"": ""<Joystick>/{Cancel}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Return"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""New Control Scheme"",
            ""bindingGroup"": ""New Control Scheme"",
            ""devices"": [
                {
                    ""devicePath"": ""<Joystick>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Pointer>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // QuestScene
        m_QuestScene = asset.FindActionMap("QuestScene", throwIfNotFound: true);
        m_QuestScene_OpenMenu = m_QuestScene.FindAction("OpenMenu", throwIfNotFound: true);
        m_QuestScene_Return = m_QuestScene.FindAction("Return", throwIfNotFound: true);
    }

    ~@QuestSceneInputActions()
    {
        UnityEngine.Debug.Assert(!m_QuestScene.enabled, "This will cause a leak and performance issues, QuestSceneInputActions.QuestScene.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // QuestScene
    private readonly InputActionMap m_QuestScene;
    private List<IQuestSceneActions> m_QuestSceneActionsCallbackInterfaces = new List<IQuestSceneActions>();
    private readonly InputAction m_QuestScene_OpenMenu;
    private readonly InputAction m_QuestScene_Return;
    public struct QuestSceneActions
    {
        private @QuestSceneInputActions m_Wrapper;
        public QuestSceneActions(@QuestSceneInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @OpenMenu => m_Wrapper.m_QuestScene_OpenMenu;
        public InputAction @Return => m_Wrapper.m_QuestScene_Return;
        public InputActionMap Get() { return m_Wrapper.m_QuestScene; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(QuestSceneActions set) { return set.Get(); }
        public void AddCallbacks(IQuestSceneActions instance)
        {
            if (instance == null || m_Wrapper.m_QuestSceneActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_QuestSceneActionsCallbackInterfaces.Add(instance);
            @OpenMenu.started += instance.OnOpenMenu;
            @OpenMenu.performed += instance.OnOpenMenu;
            @OpenMenu.canceled += instance.OnOpenMenu;
            @Return.started += instance.OnReturn;
            @Return.performed += instance.OnReturn;
            @Return.canceled += instance.OnReturn;
        }

        private void UnregisterCallbacks(IQuestSceneActions instance)
        {
            @OpenMenu.started -= instance.OnOpenMenu;
            @OpenMenu.performed -= instance.OnOpenMenu;
            @OpenMenu.canceled -= instance.OnOpenMenu;
            @Return.started -= instance.OnReturn;
            @Return.performed -= instance.OnReturn;
            @Return.canceled -= instance.OnReturn;
        }

        public void RemoveCallbacks(IQuestSceneActions instance)
        {
            if (m_Wrapper.m_QuestSceneActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IQuestSceneActions instance)
        {
            foreach (var item in m_Wrapper.m_QuestSceneActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_QuestSceneActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public QuestSceneActions @QuestScene => new QuestSceneActions(this);
    private int m_NewControlSchemeSchemeIndex = -1;
    public InputControlScheme NewControlSchemeScheme
    {
        get
        {
            if (m_NewControlSchemeSchemeIndex == -1) m_NewControlSchemeSchemeIndex = asset.FindControlSchemeIndex("New Control Scheme");
            return asset.controlSchemes[m_NewControlSchemeSchemeIndex];
        }
    }
    public interface IQuestSceneActions
    {
        void OnOpenMenu(InputAction.CallbackContext context);
        void OnReturn(InputAction.CallbackContext context);
    }
}
